### ISSUE TITLE
[v1] Implement basic Admin Controller

### ISSUE THREAD

**Issue by markhenrip** [markhenrip/Shared-Trip-server#10]
## Subtask of #5 

- [x] GET ...api/v1/admin/1/events - returns the events where userId=1 is the admin

- [x] PUT ...api/v1/admin/1/event/2/approve - approves the user that wants to join event 2 where 1 is admin (approved user's id to be taken from body)

- [x] PUT ...api/v1/admin/1/event/2/ban - same as previous but for banning

Nothing to POST or DELETE here but might move event deletion here eventually.
