### ISSUE TITLE
[v1] Implement basic Event Controller

### ISSUE THREAD

**Issue by markhenrip** [markhenrip/Shared-Trip-server#3]
## Subtask of #5 

Something like...

~~- [ ] GET ...api/v1/event?user=1 - returns the events with access info for user with the id 1~~ No, this is not good. Rather put user-related events under User Controller...

- [x] POST ...api/v1/event - creates a new event based on body

- [x] PUT ...api/v1/event/1 - updates an existing event (with the id 1) based on body

- [x] DELETE  ...api/v1/event/1 -  deletes an existing event (with the id 1)

- [x] GET ...api/v1/event/1 - returns event with the id 1

**Comment by markhenrip** [comment]
Might as well add

- [x] GET ...api/v1/event/1 - returns event with the id 1
