### ISSUE TITLE
[v1] Implement basic User Controller

### ISSUE THREAD

**Issue by markhenrip** [markhenrip/Shared-Trip-server#9]
## Subtask of #5 

- [x] GET ...api/v1/user/1 - returns user with the id 1

- [x] POST ...api/v1/user - creates a new user based on body

- [x] PUT ...api/v1/user/1 - updates an existing user (with the id 1) based on body

No DELETE needed right now.
